"""W-39 shell/script notice — REPETITION-AWARE AND CONSEQUENCE-NAMING.

# Why this file exists (2026-08-07n, PKG-19-NODE-RESTART-DIAGNOSIS)

`TOOL_CALL_THRASH_IDENTICAL_STREAK` failed `p4_ff_node_restart` at four distinct
seeds across four boundaries (98651, 99603, 90301, 91101) and at two off-family
scenarios (`revise_twice_complex`@91501, `p4_ff_python_pause`@91802). Replaying
the real `ThrashOracle` over all six preserved conversations reproduces
`count=3 allowed=2` in every one, and the prior result the repetition ignored was
a SUCCESS in every one.

The measured first broken link: **the notice and the cap are one step out of
phase.** The notice is generated BY the first repeat and deferred to the next
turn, so occurrence 2 is never warned (0 notices inside the counted group before
it, in all six runs) and the notice's single shot lands immediately before
occurrence 3 — the one that is already fatal.

Because that one shot cannot be moved earlier (detection can only happen at
occurrence 2, by which time the model has already committed to that call), the
shot has to CARRY. In the three runs where it did land in time the agent got the
shell text, which named no count and no consequence, while the plan class —
repaired under F47 — named both. This surface fired EIGHT times in one run
(07h@99603) while byte-static, which is a direct violation of GROUNDED FEEDBACK
owner constraint 4.

# What this file asserts

That the shell and script notices are repetition-aware (the exact class names a
count keyed on the same fingerprint owner the oracle grades with) and that both
name the consequence.

# Attestation binding (07m Adjudication 2, F58)

These assertions bind to the PRODUCTION constants — `_W39_CAP_CONSEQUENCE` is
imported, never re-typed. A test that attests a hand-copied duplicate of
production prose can silently stop testing the product, which is exactly the
defect F58 numbered. The one literal here is the *number*, which is the thing
under test.
"""

from __future__ import annotations

from disco.core import ActionEvent, Event, ObservationEvent, ToolCall, ToolResult
from disco.core.loop.dedup import _W39_REMINDER_SENTINEL, _w39_shell_verify_reminder

# Bound to the OWNER of the sentence, not to a re-export and not to a copy.
from disco.core.loop.dedup_notice_common import (
    _W39_CAP_CONSEQUENCE,
    _w39_identical_call_count,
)
from disco.core.tool_fingerprint import tool_call_fingerprint

_CMD = "curl -fsS http://localhost:5000/health"


def _shell_action(call_id: str, seq: int, cmd: str = _CMD) -> ActionEvent:
    # Events are frozen; `seq` is set at construction, never assigned after.
    return ActionEvent(
        seq=seq,
        thought="verifying",
        tool_call=ToolCall(tool_name="shell", call_id=call_id, arguments={"command": cmd}),
    )


def _shell_obs(action: ActionEvent, seq: int) -> ObservationEvent:
    assert action.tool_call is not None
    return ObservationEvent(
        seq=seq,
        tool_result=ToolResult(
            call_id=action.tool_call.call_id,
            tool_name="shell",
            success=True,
            content="healthy",
        ),
        action_id=action.id,
    )


def _log(n_prior: int) -> list[Event]:
    """A log of `n_prior` identical SUCCESSFUL shell calls, then the repeat.

    The repeat is `events[-1]`, which is the contract
    `_w39_shell_verify_reminder` documents (it scans `events[:-1]`).
    """
    events: list[Event] = []
    seq = 1
    for i in range(n_prior):
        action = _shell_action(f"call_{i}", seq)
        seq += 1
        obs = _shell_obs(action, seq)
        seq += 1
        events.extend([action, obs])
    events.append(_shell_action("call_repeat", seq))
    return events


def test_shell_notice_names_the_consequence() -> None:
    """The single shot the notice gets must say the run is at stake.

    Red on pre-2026-08-07n bytes: the old template ended at "instead of
    re-verifying." and named no consequence at all.
    """
    remind, prior_seq, text = _w39_shell_verify_reminder("shell", {"command": _CMD}, _log(1))
    assert remind is True
    assert prior_seq > 0
    assert _W39_REMINDER_SENTINEL in text
    assert _W39_CAP_CONSEQUENCE in text, (
        "the shell notice must name the consequence, as the plan class does; "
        "GROUNDED FEEDBACK constraint 4 forbids a static multi-fire surface"
    )


def test_shell_notice_is_repetition_aware() -> None:
    """The count must ESCALATE with the repetition, not stay static.

    This is the property owner constraint 4 actually requires ("count
    acknowledged, escalating"): the same surface firing twice in one run must
    not emit the same bytes.
    """
    _, _, first = _w39_shell_verify_reminder("shell", {"command": _CMD}, _log(1))
    _, _, second = _w39_shell_verify_reminder("shell", {"command": _CMD}, _log(2))
    assert "call number 2" in first
    assert "call number 3" in second
    assert first != second, "a multi-fire surface must not be byte-static"


def test_count_agrees_with_the_fingerprint_owner_the_oracle_grades_with() -> None:
    """The number shown and the number graded cannot disagree (A6.3 3.1)."""
    events = _log(2)
    fingerprint = tool_call_fingerprint("shell", {"command": _CMD})
    # `events[:-1]` is the log without the call about to execute.
    assert _w39_identical_call_count(events[:-1], fingerprint) == 3
    _, _, text = _w39_shell_verify_reminder("shell", {"command": _CMD}, events)
    assert "call number 3" in text


def test_notice_still_never_skips_and_stays_advisory() -> None:
    """The repair is additive rendering only — the posture is unchanged.

    `_w39_shell_verify_reminder` is a pure predicate; it returns text and the
    caller executes the command regardless. Guarding the shape here keeps a
    future edit from turning an advisory into a suppressor.
    """
    remind, _, text = _w39_shell_verify_reminder("shell", {"command": _CMD}, _log(1))
    assert remind is True
    assert "Re-run it only if you have changed something relevant" in text
    assert "act on the result you already have" in text
