"""W-39 answered-question notice — the vocabulary all three classes share.

Extracted 2026-08-07n (PKG-19-NODE-RESTART-DIAGNOSIS). The shell/script class and
the plan class say the same thing about the same cap, and until this boundary the
consequence sentence and the identical-call counter existed only on the plan side
(`dedup_plan_notice.py`, F47). Giving the shell class its own copy would have been
the F58 defect exactly — a surface bound to a COPY of the text it is about, free to
drift silently. So the shared parts live here, in the one module both import.

It sits BELOW both: it depends only on `events` and `tool_fingerprint`, so
`dedup` and `dedup_plan_notice` can each import it without a cycle (the reverse
edge, `dedup` importing `dedup_plan_notice`, is the cycle this avoids).

Why the notice needed strengthening at all — the measurement, from the four
preserved `p4_ff_node_restart` failures (98651, 99603, 90301, 91101) plus two
off-family controls:

* the real `ThrashOracle` re-run over all six reproduces `count=3 allowed=2`;
* in **all six**, the prior result the repetition ignored was a SUCCESS;
* in **all six**, the SECOND occurrence of the counted group received **zero**
  notices, because the notice is generated BY the first repeat and deferred to
  the next turn.

So the notice gets exactly one shot, and it lands immediately before the
occurrence that already fails the run. That shot cannot be moved earlier —
detection can only happen at occurrence 2, by which time the model has already
committed to that call — so it has to CARRY. The plan class already carried;
the shell class, which is the fatal class in the two most recent failures, did
not.
"""

from __future__ import annotations

from ..events import ActionEvent, Event
from ..tool_fingerprint import tool_call_fingerprint

# The consequence sentence — ONE owner, used by every notice class.
#
# It deliberately names NO NUMBER. The cap is the harness scenario's
# (`assertions.thrash.max_identical_action_repeats`), not the product's; quoting
# it here would couple product prose to a grading threshold and drift the moment
# either moved. This is why the 2026-08-07n repair is a MESSAGE repair: no cap is
# widened and no oracle weakened by it.
_W39_CAP_CONSEQUENCE = "identical repeats are capped, and the next one is held against the run"

# The escalating half, in TWO forms, because the classes can back different
# claims and neither may assert more than the log supports:
#
# * the EXACT class repeats a byte-identical call, so it can name a count keyed
#   on `tool_call_fingerprint` — the same owner `ThrashOracle` grades
#   SHAPE_IDENTICAL_STREAK with (A6.3 3.1), so the number the agent is shown and
#   the number it is graded on cannot disagree;
# * the SCRIPT class groups three different SPELLINGS of one script, so there is
#   no "that exact command" to count. It states the consequence without a count
#   rather than inventing one.
#
# Cardinals, not ordinals, on purpose: F56 (2026-08-07l) repaired a naive `{n}th`
# that rendered "the 2th time", and the plan class this mirrors already says
# "{count} times". A second ordinal site here would re-arm the defect F56 closed.
_W39_ESCALATION_CLAUSE = (
    " This is call number {count} of that exact command in this run, and it is "
    "counted: " + _W39_CAP_CONSEQUENCE + "."
)
_W39_SCRIPT_ESCALATION_CLAUSE = " Asking it again is counted: " + _W39_CAP_CONSEQUENCE + "."


def _w39_identical_call_count(events: list[Event], fingerprint: str) -> int:
    """How many times this exact call has already been issued, plus this one.

    Callers pass the PRIOR events (the log without the call about to execute);
    the ``1 +`` is that call. Verified against the preserved 07l@91101 log, where
    the plan notice renders "3 times" against real occurrences at seqs 34, 101
    and 139 — so this is not off by one.
    """
    return 1 + sum(
        1
        for e in events
        if isinstance(e, ActionEvent)
        and e.tool_call is not None
        and tool_call_fingerprint(e.tool_call.tool_name, e.tool_call.arguments) == fingerprint
    )
