"""`.env.example` (NAMES ONLY) + `SELFHOST.md` generation for the local overlay.

Extracted from ``local_compose.py`` to reduce module size; the public facade
re-imports ``_env_example`` / ``_selfhost_doc`` unchanged (indirectly, via
``emit_local_compose``).
"""

from __future__ import annotations

from disco.core.release.spec import EnvVarDecl, ReleaseSpec, SecretClass

from ._services import _ingress_service, _mount_dir, _resource_volume_names
from ._shell import _CONTAINER_PORT, _HOST_PORT_VAR


def _host_supplied_env(spec: ReleaseSpec) -> list[EnvVarDecl]:
    """The env vars the HOST must supply — every declared var that is not bound to
    a resource (bound vars are auto-provided by compose). Sorted by NAME."""
    supplied = [var for var in spec.env if var.binding is None]
    return sorted(supplied, key=lambda v: v.name)


def _env_example(spec: ReleaseSpec, host_port: int) -> str:
    lines = [
        "# .env.example — generated by Disco (local_compose).",
        "#",
        "# Copy this file to `.env` and fill in the values. It is SECRET-FREE: it",
        "# lists only variable NAMES, never values. Never commit real secrets.",
        "#",
        f"# HOST_PORT — host port to publish the app on (optional; default {host_port}).",
        f"# HOST_PORT={host_port}",
    ]
    for var in _host_supplied_env(spec):
        secrecy = "secret" if var.secret is SecretClass.secret else "public"
        need = "required" if var.required else "optional"
        lines.append("#")
        lines.append(
            f"# {var.name} — {need} {secrecy} ({var.scope.value}). "
            "Supplied by the host; never commit its value."
        )
        if var.required:
            lines.append(f"{var.name}=")
        else:
            lines.append(f"# {var.name}=")
    return "\n".join(lines) + "\n"


# ---- SELFHOST.md --------------------------------------------------------------
#
# WO-C5 #2 F3 (documented accepted limit, out of the §9 executed-artifact charter):
# `spec.name` is the user's conversation title and is rendered into SELFHOST.md
# markdown. That is a DOCS surface — it never reaches `compose.yaml` / `Dockerfile`
# (the executed artifacts), and Markdown is not executed — so a metacharacter in the
# title is at most docs-content, not command/path injection, and is intentionally NOT
# in the §9 injection boundary. As cheap defense-in-depth we still strip CR/LF and
# control characters so a crafted title cannot forge new Markdown lines/structure.


def _md_title(name: str) -> str:
    """A one-line Markdown-safe rendering of a user-supplied name for a heading —
    CR/LF and other control characters (ord < 0x20, and DEL) removed so the title
    cannot forge new Markdown lines/structure. Spaces and printable text are kept."""
    return "".join(ch for ch in name if ch >= " " and ch != "\x7f")


def _selfhost_doc(spec: ReleaseSpec) -> str:
    ingress = _ingress_service(spec)
    health = ingress.health_path or "/"
    lines = [
        f"# Self-hosting {_md_title(spec.name)}",
        "",
        "This bundle was generated by Disco (`local_compose`). It is **secret-free**:",
        "it contains only environment-variable NAMES, never values.",
        "",
        "## Prerequisites",
        "",
        "- Docker Engine with the Compose v2 plugin (`docker compose`).",
        "",
        "## Run it",
        "",
        "```sh",
        "cp .env.example .env      # then fill in the required values",
        "docker compose up -d --build",
        "```",
        "",
        f"The app is published on `127.0.0.1:${{{_HOST_PORT_VAR}:-{_CONTAINER_PORT}}}`",
        f"(override the host port by setting `{_HOST_PORT_VAR}` in `.env`).",
        "",
        "## Required environment",
        "",
    ]
    supplied = [var for var in _host_supplied_env(spec) if var.required]
    if supplied:
        for var in supplied:
            secrecy = "secret" if var.secret is SecretClass.secret else "public"
            lines.append(f"- `{var.name}` — {secrecy} ({var.scope.value}).")
    else:
        lines.append("- (none — the app needs no host-supplied environment.)")
    lines.append("")
    lines.append("## Persistent data")
    lines.append("")
    if spec.resources:
        volume_names = _resource_volume_names(spec)
        for resource in spec.resources:
            volume = volume_names[resource.id]
            lines.append(
                f"- `{resource.kind.value}` — named volume `{volume}` mounted at "
                f"`{_mount_dir(resource)}`."
            )
    else:
        lines.append("- (none — the app is stateless.)")
    lines.append("")
    lines.append("## Health")
    lines.append("")
    lines.append(f"The app is healthy when `GET {health}` returns a non-error status.")
    lines.append("")
    lines.append("## Contract")
    lines.append("")
    lines.append("`release.json` is the canonical release spec this bundle was generated from")
    lines.append("— the runtime contract. Regenerate the bundle if you edit it.")
    return "\n".join(lines) + "\n"
