/**
 * G11 — nullable source-binding contract (TYPE-LEVEL, compile-checked).
 *
 * THE GAP THIS PROVES
 * -------------------
 * The agent-server `/release` model (current/packages/agent-server/.../routes/release.py,
 * `class ReleaseResponse`) declares the source binding as NULLABLE for an
 * UNSNAPSHOTTED workspace — a project that has never been committed cannot name a
 * concrete committed source, so all three of these come back `null`:
 *
 *     spec_digest:  str | None    # null when no spec is pinned
 *     version_seq:  int | None    # null when no committed version exists
 *     tree_digest:  str | None    # null when no committed tree can be named
 *
 * The frontend wire type (current/frontend/src/types/release.ts, `ReleaseResponse`) mirrors
 * ONLY `spec_digest` as nullable. It still types the other two as NON-null:
 *
 *     spec_digest:  string | null   // ✅ matches backend
 *     version_seq:  number          // ❌ backend is `int | None`
 *     tree_digest:  string          // ❌ backend is `str | None`
 *
 * So a real `/release` payload for an unsnapshotted project (`version_seq: null`,
 * `tree_digest: null`) is a shape the TS type SWEARS is impossible. The existing
 * G11 sibling (the second `it()` in `g08-download-url-binding.test.tsx`) only
 * exercises `spec_digest: null` — a field that was ALREADY correctly nullable — so
 * it never touches the `version_seq` / `tree_digest` gap and cannot prove G11.
 *
 * WHAT THIS CONTRACT DOES
 * -----------------------
 * It annotates a `ReleaseResponse` value describing exactly that unsnapshotted
 * payload, with `spec_digest`, `version_seq`, and `tree_digest` ALL `null`. Because
 * the production type rejects `null` for `version_seq` and `tree_digest`, this is a
 * TypeScript COMPILE ERROR TODAY (RED), reported at those two properties:
 *
 *     Type 'null' is not assignable to type 'number'.   // version_seq
 *     Type 'null' is not assignable to type 'string'.   // tree_digest
 *
 * (`spec_digest: null` raises NO error — it is already `string | null` — which is
 * precisely why it does not, on its own, prove the gap.)
 *
 * PROVING GATE — do NOT edit this file to make it pass. This is a FROZEN contract.
 * It is checked in isolation by its own tsconfig:
 *
 *     cd frontend && npx tsc -p tsconfig.closeout-g11.json --noEmit   # exits NONZERO today
 *
 * It turns GREEN at R4 SOLELY by correcting the PRODUCTION type in
 * current/frontend/src/types/release.ts to mirror the backend —
 *   `version_seq: number | null;`  and  `tree_digest: string | null;`
 * — WITHOUT touching this contract. That self-discrimination (production fix flips
 * red→green; contract edit is forbidden) is what makes the red honest.
 *
 * Runtime note: this module is a pure type contract. It is a `.contract.ts` file,
 * never imported by product code and outside vitest's `.test.` glob, so it is never
 * executed or collected as a test — its ONLY job is to fail `tsc`.
 */

import type { ReleaseResponse } from "@/types/release";

/**
 * The wire payload the agent-server returns for a `/release` on an unsnapshotted
 * project: a real, extra-forbid-validated `ReleaseResponse` whose entire source
 * binding is `null`. Exported so it is a used binding (satisfies `noUnusedLocals`)
 * and so the ONLY diagnostics under `tsconfig.closeout-g11.json` are the two G11
 * nullability errors — nothing else.
 *
 * The `version_seq: null` and `tree_digest: null` properties are the RED: today the
 * production `ReleaseResponse` types them `number` / `string`, so each is
 * "Type 'null' is not assignable to type 'number' / 'string'". At R4 the production
 * type becomes `number | null` / `string | null` and this value compiles cleanly.
 */
export const unsnapshottedRelease: ReleaseResponse = {
  assessment: "needs_review",
  reasons: ["Workspace has never been committed; no source version can be named."],
  blockers: [
    {
      code: "release_field_unresolved",
      message: "commit a version before binding a self-host release",
      field: null,
      path: null,
    },
  ],
  required_env: [],
  command: "",
  ingress: null,
  self_host: false,
  // spec_digest is ALREADY `string | null` in production — this line is NOT an
  // error and is deliberately included to show the gap is the OTHER two fields.
  spec_digest: null,
  // ⬇ RED (today): backend `int | None`, frontend `number`.
  version_seq: null,
  // ⬇ RED (today): backend `str | None`, frontend `string`.
  tree_digest: null,
};
