"""Carry PDF parser warnings into source provenance without mixing concurrent reads."""

from __future__ import annotations

import logging
import threading
from collections.abc import Iterator, Sequence
from contextlib import contextmanager


class _WarningCapture(logging.Handler):
    def __init__(self) -> None:
        super().__init__(logging.WARNING)
        self.thread_id = threading.get_ident()
        self.messages: list[str] = []

    def emit(self, record: logging.LogRecord) -> None:
        if record.thread != self.thread_id or len(self.messages) > 16:
            return
        message = record.getMessage()[:400]
        if message in self.messages:
            return
        self.messages.append(
            message if len(self.messages) < 16 else "Additional parser warnings omitted."
        )


@contextmanager
def pdf_warnings() -> Iterator[list[str]]:
    """Observe this synchronous reader's warnings; leave normal logging intact."""
    logger = logging.getLogger("pypdf")
    capture = _WarningCapture()
    logger.addHandler(capture)
    try:
        yield capture.messages
    finally:
        logger.removeHandler(capture)


def annotated_pdf_text(content: str, warnings: Sequence[str]) -> str:
    """Keep readable evidence while making incomplete extraction visible to readers."""
    if not warnings:
        return content
    notice = (
        "[PDF TEXT EXTRACTION NOTICE — generated by Disco, not part of the source]\n"
        "The PDF reader reported the warnings below. Some source content may be missing "
        "or ambiguous. Do not infer that an unextracted detail is absent from the original; "
        "consult another readable version when that detail matters.\n"
        + "\n".join("- " + warning for warning in warnings)
        + "\n[END EXTRACTION NOTICE]\n\n"
    )
    return notice + content
