# syntax=docker/dockerfile:1
# Generated by Disco (local_compose) — portable, secret-free self-host image.
FROM node:22-bookworm-slim
WORKDIR /app
COPY ./ ./
RUN ["npm", "ci"]
RUN ["npm", "run", "build"]
ENV NODE_ENV=production
EXPOSE 8080
CMD ["npm", "start"]
