# syntax=docker/dockerfile:1
# Generated by Disco (local_compose) — portable, secret-free self-host image.
FROM python:3.13-slim-bookworm
WORKDIR /app
ENV PYTHONUNBUFFERED=1
COPY ./ ./
RUN ["pip", "install", "-r", "requirements.txt"]
EXPOSE 8080
CMD ["sh", "-c", "exec uvicorn main:app --host 0.0.0.0 --port ${PORT}"]
