"""Architecture diagram generation from the checked context registry."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .imports import build_import_graph, load_contexts
from .policy import REPO_ROOT

OUT_PATH = REPO_ROOT / "current" / "docs" / "architecture.generated.md"


def render_diagram(root: Path | None = None) -> str:
    """Render the architecture diagram from the context registry and import graph.

    When ``root`` is given, loads contexts and builds the import graph from
    that root so temp-tree tests render their own diagram.
    """
    contexts = load_contexts(root)
    graph = build_import_graph(root)

    # Build the set of import edges from the graph
    import_edges: set[tuple[str, str]] = set()
    for edge in graph["package_edges"]:
        import_edges.add(tuple(edge))

    # Get DM-005 upward edge observations from the context registry
    dm005_edges: set[tuple[str, str]] = set()
    for obs in contexts.get("dm005_upward_edge_observations", []):
        # Parse "disco.tools.builtin.audio_overview -> disco.agent_server.audio_config"
        parts = obs["edge"].split(" -> ")
        if len(parts) == 2:
            from_pkg = _dep_pkg_from_module(parts[0])
            to_pkg = _dep_pkg_from_module(parts[1])
            if from_pkg and to_pkg:
                dm005_edges.add((from_pkg, to_pkg))

    # Runtime edges from the context registry
    runtime_edges = contexts.get("runtime_edges", [])

    lines = [
        "<!-- GENERATED by development/scripts/gen_arch_diagram.py — DO NOT EDIT. "
        "Re-run to refresh; the graph is derived from the checked context registry. -->",
        "",
        "# Architecture — container & package dependency map",
        "",
        "Solid arrows = Python import dependencies (auto-derived from the checked",
        "context registry). Dotted = runtime (HTTP / sandbox spawn). A thick",
        "`UPWARD` arrow marks a tracked layering violation (see `.importlinter`).",
        "Layering + size are enforced by `lint-imports` and",
        "`development/scripts/check_arch_budget.py`.",
        "",
        "```mermaid",
        "graph TD",
        '    frontend["frontend (React/Vite)"]',
        '    app_server["app-server — config/admin API"]',
        '    agent_server["agent-server — runtime + AgentLoop"]',
        '    tools["tools — sandbox + builtin tools"]',
        '    retrieval["retrieval — deep research"]',
        '    core["core — events, loop engine, LLM"]',
        '    sandbox[("sandbox container<br/>podman/gVisor")]',
        "    %% runtime (HTTP / spawn) edges — stable, not import-derived",
    ]

    for re in runtime_edges:
        label = re.get("label", "")
        lines.append(f"    {re['from']} -.{label}.-> {re['to']}")

    lines.append("    %% import edges (auto-derived from checked context registry)")

    for a, b in sorted(import_edges):
        if (a, b) in dm005_edges:
            lines.append(f"    {a} ==>|UPWARD: debt| {b}")
        else:
            lines.append(f"    {a} --> {b}")

    lines.append("    linkStyle default stroke-width:1px")
    lines.append("```")

    return "\n".join(lines) + "\n"


def _dep_pkg_from_module(mod: str) -> str | None:
    """Return the full ``disco.<pkg>`` a dotted module name belongs to, else None.

    The import graph uses full ``disco.<package>`` names (e.g. ``disco.tools``),
    so the DM-005 edge conversion must produce the same form for matching.
    """
    parts = mod.split(".")
    if len(parts) >= 2 and parts[0] == "disco":
        return f"disco.{parts[1]}"
    return None


def check_diagram(root: Path | None = None) -> dict[str, Any]:
    """Check whether the tracked diagram matches the generated one.

    When ``root`` is given, renders the diagram from that root and compares
    against the root's ``current/docs/architecture.generated.md``.
    """
    if root is None:
        root = REPO_ROOT
    out_path = root / "current" / "docs" / "architecture.generated.md"
    generated = render_diagram(root)
    if out_path.is_file():
        existing = out_path.read_text(encoding="utf-8")
    else:
        existing = ""
    return {
        "ok": existing == generated,
        "path": str(out_path.relative_to(root)),
        "stale": existing != generated,
    }


def write_diagram(root: Path | None = None) -> str:
    """Write the generated diagram to the tracked path.

    When ``root`` is given, writes to that root's ``current/docs/architecture.generated.md``.
    """
    if root is None:
        root = REPO_ROOT
    out_path = root / "current" / "docs" / "architecture.generated.md"
    content = render_diagram(root)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return str(out_path.relative_to(root))
