"""Dockerfile emission (node / python / static) + the shared `build:` block.

Extracted from ``local_compose.py`` to reduce module size; the public facade
re-imports ``_dockerfile_for`` / ``_dockerignore`` unchanged (indirectly, via
``emit_local_compose``).

Two genuine cross-module dependencies are resolved with a LAZY (function-body)
import rather than a module-level one, to avoid a load-time circular import:

* ``_arg_lines`` needs ``_build_arg_names`` from the sibling ``_services``
  module — which in turn needs ``_build_block`` (defined here) at module level,
  so a top-level import here would be a genuine load-time cycle.
* ``_dockerfile_ref`` needs the public ``DOCKERFILE_PATH`` constant, which stays
  defined in the parent ``local_compose`` module (part of its public surface);
  importing the parent at module scope here would import a module that is
  itself still in the middle of importing this one.
"""

from __future__ import annotations

import json

from disco.core.release.spec import ReleaseService, ReleaseSpec, RuntimeStrategy

from ._shell import _CONTAINER_PORT, _cmd_line, _copy_line, _is_subroot, _norm_root, _run_line
from ._yaml import _Yaml

# Base images, pinned to a major so the bundle is reproducible without chasing
# `latest`. Neutral, widely-mirrored images (no vendor lock-in).
_NODE_IMAGE = "node:22-bookworm-slim"
_PYTHON_IMAGE = "python:3.13-slim-bookworm"
_STATIC_IMAGE = "busybox:1.37"

_DOCKERFILE_HEADER = (
    "# syntax=docker/dockerfile:1\n"
    "# Generated by Disco (local_compose) — portable, secret-free self-host image.\n"
)

# The `selfhost/<service>.Dockerfile` directory used for a multi-service release.
# Needed both here (`_dockerfile_ref`) and by the parent facade's
# `emit_local_compose`, which imports it back from this module (parent importing
# from a sibling part is always the safe direction).
_SELFHOST_DIR = "selfhost"


def _effective_install_cmd(service: ReleaseService) -> tuple[str, ...]:
    """The install command to emit before a build. A build-requiring service MUST
    install its dependencies first, or the image builds against no dependencies. If
    the spec supplied an explicit `install_cmd`, use it; otherwise, when the service
    declares a `build_cmd` but no install, derive a conservative default from the
    runtime (npm ci when a lockfile is declared, else npm install; pip for python)
    so any build-requiring bundle is buildable. A service with neither an install
    nor a build gets no install line."""
    if service.install_cmd:
        return service.install_cmd
    if not service.build_cmd:
        return ()
    if service.runtime is RuntimeStrategy.python:
        return ("pip", "install", ".")
    # node / static build toolchains are npm-based in this adapter.
    if service.lockfile:
        return ("npm", "ci")
    return ("npm", "install")


def _arg_lines(spec: ReleaseSpec) -> list[str]:
    """`ARG <NAME>` declarations for every build-scope PUBLIC env var, placed after
    `WORKDIR` so the build var is visible to the subsequent install/build `RUN`
    steps. Emitted as a bare `ARG` (no default) — the value flows in from the Compose
    `build.args` guard, never persisted with `ENV`, so it is absent from the final
    runtime environment."""
    from ._services import _build_arg_names

    return [f"ARG {name}" for name in _build_arg_names(spec)]


def _node_dockerfile(spec: ReleaseSpec, service: ReleaseService) -> str:
    lines = [_DOCKERFILE_HEADER.rstrip("\n"), f"FROM {_NODE_IMAGE}", "WORKDIR /app"]
    lines.extend(_arg_lines(spec))
    lines.append(_copy_line(service.root, "./"))
    install = _effective_install_cmd(service)
    if install:
        lines.append(_run_line(install))
    if service.build_cmd:
        lines.append(_run_line(service.build_cmd))
    lines.append("ENV NODE_ENV=production")
    lines.append(f"EXPOSE {_CONTAINER_PORT}")
    start = service.start_cmd or ("npm", "start")
    lines.append(_cmd_line(start))
    return "\n".join(lines) + "\n"


def _python_dockerfile(spec: ReleaseSpec, service: ReleaseService) -> str:
    lines = [_DOCKERFILE_HEADER.rstrip("\n"), f"FROM {_PYTHON_IMAGE}", "WORKDIR /app"]
    lines.append("ENV PYTHONUNBUFFERED=1")
    lines.extend(_arg_lines(spec))
    lines.append(_copy_line(service.root, "./"))
    install = _effective_install_cmd(service)
    if install:
        lines.append(_run_line(install))
    if service.build_cmd:
        lines.append(_run_line(service.build_cmd))
    lines.append(f"EXPOSE {_CONTAINER_PORT}")
    start = service.start_cmd or ("python", "-m", "http.server", str(_CONTAINER_PORT))
    lines.append(_cmd_line(start))
    return "\n".join(lines) + "\n"


def _dir_token(value: str | None) -> str:
    """Normalize a path fragment to a bare directory token (`""` for the root)."""
    if value is None:
        return ""
    token = value.strip().rstrip("/")
    if token.startswith("./"):
        token = token[2:]
    return "" if token in ("", ".") else token


def _static_src(root: str, output_dir: str | None) -> str:
    """The build-context source dir for a prebuilt static site — `root/output_dir`
    normalized, or `./` for the workspace root."""
    parts = [p for p in (_dir_token(root), _dir_token(output_dir)) if p]
    return "./" if not parts else "/".join(parts) + "/"


def _static_dockerfile(spec: ReleaseSpec, service: ReleaseService) -> str:
    lines = [_DOCKERFILE_HEADER.rstrip("\n")]
    out_token = _dir_token(service.output_dir)
    if service.build_cmd:
        # Two-stage: build the assets with node, serve them from a tiny static
        # image so the shipped image carries no build toolchain.
        lines.append(f"FROM {_NODE_IMAGE} AS build")
        lines.append("WORKDIR /app")
        lines.extend(_arg_lines(spec))
        lines.append(_copy_line(service.root, "./"))
        install = _effective_install_cmd(service)
        if install:
            lines.append(_run_line(install))
        lines.append(_run_line(service.build_cmd))
        lines.append(f"FROM {_STATIC_IMAGE}")
        lines.append("WORKDIR /site")
        built = f"/app/{out_token}/" if out_token else "/app/"
        lines.append(f"COPY --from=build {built} /site/")
    else:
        lines.append(f"FROM {_STATIC_IMAGE}")
        lines.append("WORKDIR /site")
        lines.append(f"COPY {_static_src(service.root, service.output_dir)} /site/")
    lines.append(f"EXPOSE {_CONTAINER_PORT}")
    lines.append(
        "CMD "
        + json.dumps(
            ["busybox", "httpd", "-f", "-v", "-p", str(_CONTAINER_PORT), "-h", "/site"],
            ensure_ascii=False,
        )
    )
    return "\n".join(lines) + "\n"


def _dockerfile_for(spec: ReleaseSpec, service: ReleaseService) -> str | None:
    """The Dockerfile text for a service, or `None` for a `container` service
    (which ships its own Dockerfile — we reference, never emit/overwrite it)."""
    if service.runtime is RuntimeStrategy.node:
        return _node_dockerfile(spec, service)
    if service.runtime is RuntimeStrategy.python:
        return _python_dockerfile(spec, service)
    if service.runtime is RuntimeStrategy.static:
        return _static_dockerfile(spec, service)
    if service.runtime is RuntimeStrategy.container:
        return None
    # `dev_server` (AppKit) is handled BEFORE this generic loop, by
    # `_emit_dev_server_overlay` (its whole compose shape differs). Reaching here
    # with one is a bug — fail loud rather than emit a silently-wrong bundle.
    raise ValueError(
        f"local_compose has no generic Dockerfile for runtime strategy "
        f"{service.runtime.value!r} (dev_server is emitted via its own overlay); "
        f"got service {service.id!r}"
    )


# ---- .dockerignore ------------------------------------------------------------


def _dockerignore() -> str:
    entries = [
        "# Generated by Disco (local_compose).",
        "# Keeps secrets and build cruft out of the image build context.",
        ".git",
        ".gitignore",
        ".gitattributes",
        "node_modules",
        ".venv",
        "venv",
        "__pycache__",
        "*.pyc",
        "*.pyo",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".disco",
        "*.log",
        ".DS_Store",
        ".env",
        ".env.*",
        "!.env.example",
        # workerd dev secrets (`.dev.vars`, `.dev.vars.production`, …): a stray host
        # one — if the owner ran `wrangler dev` before building — must never enter an
        # image layer. The committed `.dev.vars.example` placeholder stays included.
        ".dev.vars",
        ".dev.vars.*",
        "!.dev.vars.example",
    ]
    return "\n".join(entries) + "\n"


# ---- build block + Dockerfile paths -------------------------------------------


def _dockerfile_ref(service: ReleaseService, *, multi: bool) -> str:
    """The `build.dockerfile` a service's compose block points at."""
    from disco.core.release.local_compose import DOCKERFILE_PATH

    if service.runtime is RuntimeStrategy.container:
        # The app ships its own Dockerfile at its root; reference, never emit.
        if _is_subroot(service.root):
            return f"{_norm_root(service.root)}/{DOCKERFILE_PATH}"
        return DOCKERFILE_PATH
    if multi:
        return f"{_SELFHOST_DIR}/{service.id}.Dockerfile"
    return DOCKERFILE_PATH


def _build_block(service: ReleaseService, *, multi: bool) -> dict[str, _Yaml]:
    return {"context": ".", "dockerfile": _dockerfile_ref(service, multi=multi)}
