"""disco.core — the brain (no server, no UI).

Phase 0 surfaces the Event & State spine (event-state-contract.md). Later phases
add the agent loop, the real condenser, the LLM router, and security here.
"""

from __future__ import annotations

from .dod import (
    DoDPredicate,
    DoDSpec,
    DoDSpecAlreadySet,
    predicate_from_obj,
    predicate_to_dict,
)
from .dod_evaluator import (
    CommandResult,
    DoDEvaluator,
    DoDPredicateResult,
    DoDVerdict,
    HttpProbeResult,
    LLMSubjectiveJudge,
    PathEscapeError,
    SubjectiveJudge,
    SubjectiveJudgeRequest,
    SubjectiveVerdict,
    resolve_under_workspace,
    spec_fingerprint,
)
from .equality import event_content_eq
from .events import (
    SCHEMA_VERSION,
    ActionEvent,
    AgentErrorEvent,
    AlternativeOption,
    AlternativesEvent,
    BaseEvent,
    ClarifyEvent,
    ClarifyQuestionItem,
    CondensationEvent,
    ContextResolvedEvent,
    ContextSummaryEvent,
    ConversationStatus,
    DatasourceEvent,
    DeliverableEvent,
    ErrorEvent,
    Event,
    EventAdapter,
    EventKind,
    EventSource,
    KnowledgeEvent,
    LLMConvertible,
    LLMMessage,
    MessageEvent,
    ObservationEvent,
    PlanEvent,
    PlanStep,
    PlanVerificationTransition,
    PlanVerifierFailure,
    QuestionsV2Event,
    QuestionsV2Item,
    ReportEvent,
    ReportSection,
    SecurityRisk,
    StatusEvent,
    ToolCall,
    ToolResult,
    VerifierShadowEvent,
    VerifierStartedEvent,
    VerifierVerdictEvent,
    WorkspaceRestoredEvent,
    WorkspaceVersionEvent,
    event_from_json_dict,
    event_to_json_dict,
)
from .migration import migrate_event
from .skills import Skill, SkillStore, render_skills_for_prompt, slugify
from .state import ConversationState
from .store.base import ConversationSummary, EventFilter, EventStore, Page
from .store.sqlite import DEFAULT_OWNER_ID, SqliteEventStore, install_owner_id
from .view import (
    CondensationRequest,
    Condenser,
    LLMSummarizingCondenser,
    NoOpCondenser,
    Summarizer,
    View,
)
from .wire import FileStreamFrame, WSClientFrame, WSServerFrame

__all__ = [
    "SCHEMA_VERSION",
    "ActionEvent",
    "AgentErrorEvent",
    "AlternativeOption",
    "AlternativesEvent",
    "BaseEvent",
    "ClarifyEvent",
    "ClarifyQuestionItem",
    "CondensationEvent",
    "CondensationRequest",
    "Condenser",
    "ContextResolvedEvent",
    "ContextSummaryEvent",
    "ConversationState",
    "ConversationStatus",
    "ConversationSummary",
    "DEFAULT_OWNER_ID",
    "install_owner_id",
    "DoDPredicate",
    "DoDEvaluator",
    "DoDPredicateResult",
    "DoDSpec",
    "DoDSpecAlreadySet",
    "DoDVerdict",
    "DatasourceEvent",
    "DeliverableEvent",
    "ErrorEvent",
    "Event",
    "EventAdapter",
    "EventFilter",
    "EventKind",
    "EventSource",
    "EventStore",
    "FileStreamFrame",
    "HttpProbeResult",
    "KnowledgeEvent",
    "LLMConvertible",
    "LLMMessage",
    "LLMSubjectiveJudge",
    "MessageEvent",
    "MessageEvent",
    "LLMSummarizingCondenser",
    "NoOpCondenser",
    "ObservationEvent",
    "Page",
    "PathEscapeError",
    "PlanEvent",
    "PlanStep",
    "PlanVerificationTransition",
    "PlanVerifierFailure",
    "QuestionsV2Event",
    "QuestionsV2Item",
    "ReportEvent",
    "SubjectiveJudge",
    "SubjectiveJudgeRequest",
    "SubjectiveVerdict",
    "predicate_from_obj",
    "predicate_to_dict",
    "ReportSection",
    "CommandResult",
    "SecurityRisk",
    "Skill",
    "SkillStore",
    "SqliteEventStore",
    "render_skills_for_prompt",
    "slugify",
    "StatusEvent",
    "Summarizer",
    "ToolCall",
    "ToolResult",
    "VerifierShadowEvent",
    "VerifierStartedEvent",
    "VerifierVerdictEvent",
    "WorkspaceVersionEvent",
    "WorkspaceRestoredEvent",
    "View",
    "WSClientFrame",
    "WSServerFrame",
    "event_content_eq",
    "event_from_json_dict",
    "event_to_json_dict",
    "migrate_event",
    "resolve_under_workspace",
    "spec_fingerprint",
]
