# syntax=docker/dockerfile:1
# Generated by Disco (local_compose) — portable, secret-free self-host image.
FROM busybox:1.37
WORKDIR /site
COPY ./ /site/
EXPOSE 8080
CMD ["busybox", "httpd", "-f", "-v", "-p", "8080", "-h", "/site"]
