#!/usr/bin/env python3
"""Generate the architecture container/dependency diagram from the ACTUAL imports.

Run on demand / in CI; never hand-edit the output. The whole point is that the
diagram is derived from the code, so it cannot drift. Emits Mermaid into
docs/architecture.generated.md (a generated artifact, safe to overwrite).

    python3 scripts/gen_arch_diagram.py        # write the file
    python3 scripts/gen_arch_diagram.py --check # CI: fail if the file is stale
"""

from __future__ import annotations

import ast
import os
import sys

PKGS = ["core", "retrieval", "tools", "agent_server", "app_server"]
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "docs", "architecture.generated.md")
# package dir name on disk (uv workspace uses hyphens for two of them)
DIR = {"agent_server": "agent-server", "app_server": "app-server"}


def _dep_pkg(mod: str | None) -> str | None:
    """The disco.<pkg> a dotted module name belongs to, else None."""
    if not mod:
        return None
    parts = mod.split(".")
    if len(parts) >= 2 and parts[0] == "disco" and parts[1] in PKGS:
        return parts[1]
    return None


def edges() -> set[tuple[str, str]]:
    """REAL import edges only (AST-parsed — strings/comments don't count),
    including function-local imports, matching import-linter/grimp's view."""
    out: set[tuple[str, str]] = set()
    for pkg in PKGS:
        src = os.path.join(ROOT, "packages", DIR.get(pkg, pkg), "src")
        for dp, _, files in os.walk(src):
            if "__pycache__" in dp:
                continue
            for f in files:
                if not f.endswith(".py"):
                    continue
                try:
                    tree = ast.parse(open(os.path.join(dp, f), encoding="utf-8").read())
                except SyntaxError:
                    continue
                for node in ast.walk(tree):
                    dep = None
                    if isinstance(node, ast.ImportFrom):
                        dep = _dep_pkg(node.module)
                    elif isinstance(node, ast.Import):
                        for n in node.names:
                            d = _dep_pkg(n.name)
                            if d and d != pkg:
                                out.add((pkg, d))
                    if dep and dep != pkg:
                        out.add((pkg, dep))
    return out


# Known upward violation tracked in .importlinter (rendered as a dashed red edge).
VIOLATIONS = {("tools", "agent_server")}


def mermaid(es: set[tuple[str, str]]) -> str:
    lines = [
        "```mermaid",
        "graph TD",
        "    frontend[\"frontend (React/Vite)\"]",
        "    app_server[\"app-server — config/admin API\"]",
        "    agent_server[\"agent-server — runtime + AgentLoop\"]",
        "    tools[\"tools — sandbox + builtin tools\"]",
        "    retrieval[\"retrieval — deep research\"]",
        "    core[\"core — events, loop engine, LLM\"]",
        "    sandbox[(\"sandbox container<br/>podman/gVisor\")]",
        "    %% runtime (HTTP / spawn) edges — stable, not import-derived",
        "    frontend -.HTTP.-> agent_server",
        "    frontend -.HTTP.-> app_server",
        "    agent_server -.spawns.-> sandbox",
        "    %% import edges (auto-derived)",
    ]
    for a, b in sorted(es):
        if (a, b) in VIOLATIONS:
            lines.append(f"    {a} ==>|UPWARD: debt| {b}")
        else:
            lines.append(f"    {a} --> {b}")
    lines.append("    linkStyle default stroke-width:1px")
    lines.append("```")
    return "\n".join(lines)


def render(es: set[tuple[str, str]]) -> str:
    return (
        "<!-- GENERATED by scripts/gen_arch_diagram.py — DO NOT EDIT. "
        "Re-run to refresh; the graph is derived from the code's imports. -->\n\n"
        "# Architecture — container & package dependency map\n\n"
        "Solid arrows = Python import dependencies (auto-derived). Dotted = runtime\n"
        "(HTTP / sandbox spawn). A thick `UPWARD` arrow marks a tracked layering\n"
        "violation (see `.importlinter`). Layering + size are enforced by\n"
        "`lint-imports` and `scripts/check_arch_budget.py`.\n\n"
        + mermaid(es) + "\n"
    )


def main() -> int:
    content = render(edges())
    check = "--check" in sys.argv
    if check:
        existing = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if existing != content:
            print("STALE: docs/architecture.generated.md is out of date — run "
                  "`python3 scripts/gen_arch_diagram.py`.")
            return 1
        print("architecture diagram up to date.")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write(content)
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(edges())} import edges)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
