#!/usr/bin/env python3
"""BP-00 V2 criteria (c)+(d): a REAL image turn end-to-end against the live
vision-profile driver, with the screenshot produced by the ACTUAL BP-04 browser
daemon (1280x800 Chromium viewport, same module the sandbox runs).

Flow:
  1. build a small visually-distinctive test page, serve it on 127.0.0.1:8123
  2. run the BP-04 daemon (PMX_WORKSPACE=tmp, loopback :8901), POST navigate
  3. take its screenshot -> test-record/bp-00/screenshot-image-turn.png
  4. (d) send the screenshot as an OpenAI image_url content part to :18080,
     ask what is visible; print the answer for the bench record
  5. (c) repeat with ~8K tokens of text context + the image, sampling VRAM/GTT
     through the turn (KV for the full 128K ctx is preallocated at load; this
     exercises the mmproj + compute buffers on top)

Evidence: stdout transcript + screenshot-image-turn.png + image-turn.json.
"""

from __future__ import annotations

import base64
import json
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import urllib.request
from pathlib import Path

API = "http://127.0.0.1:18080"
GPU = Path("/sys/class/drm/card1/device")
OUT = Path(__file__).parent
REPO = OUT.parent.parent

PAGE = """<!doctype html><html><head><title>PMX Status Dashboard</title><style>
body{background:#101418;color:#e8e8e8;font-family:sans-serif;margin:0}
header{background:#ff6a00;color:#101418;padding:18px 28px;font-size:24px;font-weight:700}
.cards{display:flex;gap:18px;padding:28px}
.card{background:#1b222b;border-radius:10px;padding:22px;flex:1}
.card h2{margin:0 0 8px;font-size:15px;color:#9ab}
.card .v{font-size:34px;font-weight:700;color:#6fe09a}
</style></head><body>
<header>PMX Status Dashboard</header>
<div class="cards">
<div class="card"><h2>Builds today</h2><div class="v">42</div></div>
<div class="card"><h2>Tests passing</h2><div class="v">668</div></div>
<div class="card"><h2>Driver speed</h2><div class="v">50 t/s</div></div>
</div></body></html>"""


def vram() -> dict[str, int]:
    rd = lambda n: int((GPU / n).read_text()) // 1048576
    return {"vram_used_mib": rd("mem_info_vram_used"), "gtt_used_mib": rd("mem_info_gtt_used")}


def wait_port(url: str, tries: int = 40) -> None:
    for _ in range(tries):
        try:
            urllib.request.urlopen(url, timeout=2)
            return
        except Exception:
            time.sleep(0.5)
    raise RuntimeError(f"never came up: {url}")


def post_json(url: str, body: dict, timeout: int = 600) -> dict:
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(), headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.load(r)


def image_chat(question: str, b64: str, filler: str = "") -> tuple[dict, dict]:
    """One vision chat turn; returns (response, peak vram/gtt sampled during)."""
    peak = {"vram_used_mib": 0, "gtt_used_mib": 0}
    stop = threading.Event()

    def sampler():
        while not stop.is_set():
            v = vram()
            peak["vram_used_mib"] = max(peak["vram_used_mib"], v["vram_used_mib"])
            peak["gtt_used_mib"] = max(peak["gtt_used_mib"], v["gtt_used_mib"])
            time.sleep(0.25)

    t = threading.Thread(target=sampler, daemon=True)
    t.start()
    try:
        content = []
        if filler:
            content.append({"type": "text", "text": filler})
        content.append({"type": "text", "text": question})
        content.append(
            {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}}
        )
        res = post_json(
            f"{API}/v1/chat/completions",
            {
                "model": "driver",
                "messages": [{"role": "user", "content": content}],
                # Qwen3.6 thinks by default — leave room for reasoning AND the
                # final content (200 was eaten entirely by reasoning_content).
                "max_tokens": 900,
                "temperature": 0,
            },
        )
    finally:
        stop.set()
        t.join(timeout=2)
    return res, peak


def generate_screenshot_locally(tmp: Path, dest: Path, record: dict) -> None:
    """Local daemon path — kept for reference; NOT used for the gate record.
    Playwright's Ubuntu-built Chromium renders ZERO glyphs on this Fedora
    Atomic host (fonts present, fc-list fine — host quirk). The gate screenshot
    is generated by the SAME daemon inside pmx-sandbox:base under gVisor on
    VM-201 (the actual production rendering path) via bp00-shot-remote.sh."""
    (tmp / "site").mkdir()
    (tmp / "site" / "index.html").write_text(PAGE)
    http_srv = subprocess.Popen(
        [sys.executable, "-m", "http.server", "8123", "--bind", "127.0.0.1"],
        cwd=tmp / "site", stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    daemon = subprocess.Popen(
        [str(REPO / ".venv/bin/python"), "-m", "disco.tools.builtin._browser_daemon"],
        env={**os.environ, "PMX_WORKSPACE": str(tmp)},
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    try:
        wait_port("http://127.0.0.1:8123/")
        wait_port("http://127.0.0.1:8901/health")
        nav = post_json(
            "http://127.0.0.1:8901/action",
            {"action": "navigate", "url": "http://127.0.0.1:8123/"},
            timeout=60,
        )
        assert nav.get("ok"), f"daemon navigate failed: {nav}"
        shutil.copy(tmp / nav["screenshot_path"], dest)
        record["daemon"] = {"url": nav["url"], "title": nav["title"], "console": nav["console"]}
    finally:
        daemon.terminate()
        http_srv.terminate()


def main() -> int:
    record: dict = {"date": time.strftime("%Y-%m-%d %H:%M:%S"), "vram_idle": vram()}
    tmp = Path(tempfile.mkdtemp(prefix="bp00-"))
    dest = OUT / "screenshot-image-turn.png"

    if "--generate-local" in sys.argv:
        generate_screenshot_locally(tmp, dest, record)
        print(f"daemon screenshot (LOCAL — glyphless on this host): {dest}")
    else:
        # Default: the screenshot already on disk, produced by the BP-04 daemon
        # inside pmx-sandbox:base under gVisor on VM-201 (bp00-shot-remote.sh).
        assert dest.exists(), f"missing {dest} — run bp00-shot-remote.sh on VM-201 first"
        record["daemon"] = {
            "source": "pmx-sandbox:base @ VM-201 (gVisor, runsc) via bp00-shot-remote.sh",
            "title": "PMX Status Dashboard",
        }
        print(f"using sandbox-generated screenshot: {dest} ({dest.stat().st_size} bytes)")

    try:
        b64 = base64.b64encode(dest.read_bytes()).decode()

        # --- (d) plain image turn ----------------------------------------
        res, peak = image_chat(
            "This is a screenshot of a web page. Describe exactly what you see: "
            "the page title/header, the layout, and any numbers shown.", b64
        )
        ans = res["choices"][0]["message"]["content"]
        record["image_turn"] = {"answer": ans, "usage": res.get("usage"),
                                "timings": res.get("timings"), "peak": peak}
        print(f"\n--- (d) image-turn answer ---\n{ans}\n")
        print(f"(d) peak during turn: {peak}, timings: {res.get('timings')}")

        # --- (c) long-context + image turn --------------------------------
        filler = " ".join(
            f"Log line {i}: build step completed with status OK and duration {i % 97} ms."
            for i in range(700)
        )  # ~8-9K tokens of plausible context
        res2, peak2 = image_chat(
            "Given the long log above AND the screenshot, answer briefly: what does "
            "the page header say, and what status do the log lines report?",
            b64, filler=filler,
        )
        ans2 = res2["choices"][0]["message"]["content"]
        record["long_ctx_image_turn"] = {"answer": ans2[:500], "usage": res2.get("usage"),
                                         "timings": res2.get("timings"), "peak": peak2}
        print(f"\n--- (c) long-ctx+image answer (first 300 chars) ---\n{ans2[:300]}\n")
        print(f"(c) prompt tokens: {res2.get('usage', {}).get('prompt_tokens')}, peak: {peak2}")

        record["vram_after"] = vram()
        (OUT / "image-turn.json").write_text(json.dumps(record, indent=2))
        print(f"\nsaved {OUT / 'image-turn.json'}")
        return 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
